<BlockChain>

<AI>

<English>

<Bot>

<Law>

<Work>

<Python>

------------------------------------------------------------------------

------------------------------------------------------------------------

<git>

------------------------------------------------------------------------
・NG
同じブランチで、pull前に同じ行に複数ユーザが同じファイルを更新した場合

ユーザ1がbbb.txtを空からSSSに更新
ユーザ2がbbb.txtを空からGGGに更新

・ユーザ1のpush
$ git push origin master
Fatal: HttpRequestException encountered.
Username for 'https://github.com': misawa0616
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 270 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To https://github.com/misawa0616/git_tutorial_back
   d5431ee..e78f758  master -> master


・ユーザ2がユーザ1のpushの上から、pushしようとしたところ、エラー
C:\Users\81805\Desktop\test>git push origin master
Fatal: HttpRequestException encountered.
Username for 'https://github.com': misawa0616
Password for 'https://misawa0616@github.com':
To https://github.com/misawa0616/git_tutorial_back.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/misawa0616/git_tutorial_back.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

・pullも失敗する。
C:\Users\81805\Desktop\test>git pull origin master
From https://github.com/misawa0616/git_tutorial_back
 * branch            master     -> FETCH_HEAD
Updating d5431ee..e78f758
error: Your local changes to the following files would be overwritten by merge:
        bbb.txt
Please commit your changes or stash them before you can merge.
Aborting


・ユーザ2のコミットを戻すなどして対処する必要がある。競合してはならない
git reset --hard

------------------------------------------------------------------------